---
- hosts: test
  remote_user: root

  tasks:
  - name: stop gluster volume distvol
    gluster_volume:
      state: stopped
      name: distvol
    ignore_errors: yes

  - name: stop gluster volume repvol
    gluster_volume:
      state: stopped
      name: repvol
    ignore_errors: yes

  - name: remove gluster volume distvol
    gluster_volume:
      state: absent
      name: distvol
    ignore_errors: yes

  - name: remove gluster volume repvol
    gluster_volume:
      state: absent
      name: repvol
    ignore_errors: yes

  - name: remove rhgs4, rhgs5 and rhgs6 from the list of trusted hosts
    command: sudo gluster peer detach "{{ item }}"
    with_items:
      - rhgs4
      - rhgs5
      - rhgs6
    ignore_errors: yes

  - name: create ssh keys for root
    user:
      name: root
      generate_ssh_key: yes

  - name: retrieve ssh public key for root from rhgs1
    shell: cat /root/.ssh/id_rsa.pub
    register: ssh_keys
    tags:
      - ssh

  - debug:
      msg: "{{ ssh_keys.stdout }}"
    tags:
      - ssh                                                                                                                                                                  
                                                                                                                                                                             
  - name: deploy ssh key on rhgs4                                                                                                                                            
    authorized_key: user=root key= "{{ ssh_keys.stdout }}"                                                                                                                   
    delegate_to: rhgs4  

