---
- hosts: all
  remote_user: root

  - name: Clear LVM
    lvg:
      vg: "{{ item }}"
      state: absent
      force: yes
    with_items: 
      - rhgs_vg1
      - rhgs_vg2
      - rhgs_vg3


- hosts: rhgs1
  remote_user: root

  tasks:

  - name: stop gluster volume repvol
    gluster_volume:
      state: stopped
      name: repvol
    ignore_errors: yes

  - name: stop gluster volume distvol
    gluster_volume:
      state: stopped
      name: distvol
    ignore_errors: yes

  - name: stop gluster volume mastervol
    gluster_volume:
      state: stopped
      name: mastervol
    ignore_errors: yes

  - name: remove gluster volume repvol
    gluster_volume:
      state: absent
      name: repvol
    ignore_errors: yes

  - name: remove gluster volume distvol
    gluster_volume:
      state: absent
      name: distvol
    ignore_errors: yes

  - name: remove gluster volume mastervol
    gluster_volume:
      state: absent
      name: mastervol
    ignore_errors: yes

  - name: copy materials to rhgs2
    copy:
      src: /home/student/materials/
      dest: /home/student/materials/
      owner: student
      group: student
      mode: 0644

  - name: create a new cluster with rhgs1 and rhgs2 as members
    command: sudo gluster peer probe "{{ item}}"
    with_items:
      - rhgs2

- hosts: rhgs2
  remote_user: root

  tasks:

  - name: copy materials to rhgs2
    copy:
      src: /home/student/materials/
      dest: /home/student/materials/
      owner: student
      group: student
      mode: 0644


- hosts: rhgs4
  remote_user: root

  tasks:

  - name: stop gluster volume slavevol
    gluster_volume:
      state: stopped
      name: slavevol
    ignore_errors: yes

  - name: remove gluster volume slavevol
    gluster_volume:
      state: absent
      name: slavevol
    ignore_errors: yes

