---                                 
- hosts: all                        
  remote_user: root                 
  tasks:                            

  - name: Ensure gluster is running on all nodes
    systemd:
      name: glusterd
      state: started

  - name: Delete snapshots if they exist                                 
    command: sudo gluster snapshot delete all                            

  - name: stop gluster service      
    systemd:                        
      name: glusterd                
      state: stopped                

  - name: Kill all remaining gluster processes                           
    shell: /bin/bash -c 'pkill -9 {{ item }}'                            
    with_items:                     
      - glusterfs                   
      - glusterfsd                  
    ignore_errors: yes              

  - name: Clear existing gluster configuration                           
    file:                           
      path: "/var/lib/glusterd/{{ item }}"                               
      state: absent                 
    with_items:                     
      - glusterd.info               
      - glustershd                  
      - bitd                        
      - glusterfind                 
      - nfs                         
      - peers                       
      - quotad                      
      - scub                        
      - snaps                       
      - ss_brick                    
      - vols                        
    ignore_errors: yes              

  - name: Start glusterd again      
    systemd:                        
      name: glusterd                
      state: started                

  - name: Umount bricks             
    mount:                          
      path: "{{ item }}"            
      state: unmounted              
    with_items:                     
      - /rhgs/brick_xvda            
      - /rhgs/brick_xvdb            
      - /rhgs/brick_xvdc            
      - /rhgs/brick_xvdd            

  - name: Clear LVM                 
    lvg:                            
      vg: "{{ item }}"              
      state: absent                 
      force: yes                    
    with_items:                     
      - rhgs_vg1                    
      - rhgs_vg2                    
      - rhgs_vg3                    


- hosts: rhgs1                      
  remote_user: root                 

  tasks:                            

  - name: create a new cluster with rhgs1 and rhgs2 as members           
    command: sudo gluster peer probe "{{ item}}"                         
    with_items:                     
      - rhgs2                       

- hosts: rhgs2                      
  remote_user: root                 

  tasks:                            

- hosts: rhgs4                      
  remote_user: root                 

  tasks:                  
